# Generated by Django 2.2.5 on 2021-11-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowCryptoTemp', '0002_scrapper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowCrypto',
            new_name='ShowCryptoTemp',
        ),
    ]
