# Generated by Django 2.2.5 on 2021-12-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowCryptoTemp', '0003_auto_20211122_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapper',
            name='author',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='score',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='selftext',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='title_vader',
        ),
    ]
