# Generated by Django 2.2.5 on 2021-12-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowCryptoTemp', '0005_auto_20211205_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapper',
            name='predict_value',
            field=models.IntegerField(null=True),
        ),
    ]
