# Generated by Django 2.2.5 on 2021-12-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowCryptoTemp', '0006_scrapper_predict_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapper_ada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('created_utc', models.IntegerField(null=True)),
                ('predict_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapper_bitcoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('created_utc', models.IntegerField(null=True)),
                ('predict_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapper_doge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('created_utc', models.IntegerField(null=True)),
                ('predict_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapper_Ethereum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('created_utc', models.IntegerField(null=True)),
                ('predict_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapper_ripple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('created_utc', models.IntegerField(null=True)),
                ('predict_value', models.IntegerField(null=True)),
            ],
        ),
    ]
