# Generated by Django 2.2.5 on 2021-12-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowCryptoTemp', '0007_scrapper_ada_scrapper_bitcoin_scrapper_doge_scrapper_ethereum_scrapper_ripple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scrapper',
        ),
        migrations.DeleteModel(
            name='Scrapper_ada',
        ),
        migrations.DeleteModel(
            name='Scrapper_ripple',
        ),
    ]
